### ISSUE TITLE
How to evaluate local custom models?

### ISSUE THREAD

**Issue by VoiceBeer** [gersteinlab/ML-Bench#2]
Hi, thx for the work. Is there any way to evaluate custom models on this benchmark?

**Comment by Liu-yuliang** [comment]
Thank you for your attention to the work. We are in the process of organizing the execution environment, and we will release the Docker image and its usage instruction within a week.

**Comment by VoiceBeer** [comment]
Thx, looking forward to the next process :>

**Comment by tangxiangru** [comment]
@VoiceBeer Hi, you can check this: https://github.com/gersteinlab/ML-Bench/tree/master/Execution%20env.
Hope that helps!

**Comment by VoiceBeer** [comment]
Hey thx, i'll check it out
