### ISSUE TITLE
The GPT3.5 result could not be reproduced

### ISSUE THREAD

**Issue by iiinsight** [gersteinlab/ML-Bench#3]
I found that two parameters in script/run.sh were running incorrectly, where the type="quarter" parameter was not defined or used in query_gpt.py. The instructions="extend_instructions" parameter also returns KeyError: 'extend_instructions'
How do I reproduce the GPT3.5 results in the paper in ML-Bench?

![image](https://github.com/gersteinlab/ML-Bench/assets/108727971/35bb068c-0a59-493e-a4e2-f5e69047b29e)

![image](https://github.com/gersteinlab/ML-Bench/assets/108727971/455ea120-7b7d-4e54-85c2-50f4775d56da)

`Processing the data.
  0%|                                                                                                                                                              | 0/292 [00:00<?, ?it/s] 
Traceback (most recent call last):
  File "query_gpt.py", line 239, in <module>
    extend_instructions=line[f'{args.instruction}']
KeyError: 'extend_instructions'
(py38torch1101)
`

**Comment by super-dainiu** [comment]
Hi, the key for instruction should be 'instruction' instead of 'extend_instructions'. It might be caused by version updates.
